services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/shozai_app/Dockerfile
    ports:
      - "1323:1323"
      - "2345:2345"
    volumes:
       - ./:/home/shozai_model
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./docker/database/init.d:/docker-entrypoint-initdb.d
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
