version: "3"
services:
  db:
    build: 
      context: ./docker/database/
      dockerfile: ./Dockerfile
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./init.d/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password
